import Head from "next/head";
import Link from "next/link";
aaa;
const Contact = () => {
  return (
    <div className="font-sans" style={{ color: "#242424" }}>
      <Head>
        <title>ZION</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icoaan" href="/favicon.ico" />
      </Head>
      <header className="flex h-16 w-full shadow-md justify-between items-center mx-auto px-24 fixed z-10 bg-white ">
        <div className="block">
          <h1>
            <Link href="/" className="font-serif text-4xl">
              ZION
            </Link>
          </h1>
        </div>
        <ul className="flex text-base font-normal">
          <li>
            <Link
              href="/"
              className="no-underline hover:after:visible hover:after:opacity-100 hover:after:-bottom-1 after:duration-300 mr-3 relative inline-block after:absolute after:-bottom-2
               after:left-0 after:content-[''] after:h-2px after:w-full after:bg-under after:opacity-0 after:invisible "
            >
              ホーム
            </Link>
          </li>
          <li>
            <Link
              href="/"
              className="no-underline hover:after:visible hover:after:opacity-100 hover:after:-bottom-1 after:duration-300 mr-3 relative inline-block after:absolute after:-bottom-2
               after:left-0 after:content-[''] after:h-2px after:w-full after:bg-under after:opacity-0 after:invisible "
            >
              施工実績
            </Link>
          </li>
          <li>
            <Link
              href="/"
              className="no-underline hover:after:visible hover:after:opacity-100 hover:after:-bottom-1 after:duration-300 mr-3 relative inline-block after:absolute after:-bottom-2
               after:left-0 after:content-[''] after:h-2px after:w-full after:bg-under after:opacity-0 after:invisible "
            >
              業務内容
            </Link>
          </li>
          <li>
            <Link
              href="/contact"
              className="no-underline hover:after:visible hover:after:opacity-100 hover:after:-bottom-1 after:duration-300  relative inline-block after:absolute after:-bottom-2
               after:left-0 after:content-[''] after:h-2px after:w-full after:bg-under after:opacity-0 after:invisible "
            >
              お問い合わせ
            </Link>
          </li>
        </ul>
      </header>
      <div
        className="h-full w-full pb-10"
        style={{ backgroundColor: "#DFF3FA" }}
      >
        <div className=" mx-auto px-24 pt-16 " style={{ width: "1070px" }}>
          <div className="bg-white mt-10 text-center pb-10">
            <div style={{ width: "546px" }} className="mx-auto ">
              <h2 className="pt-10  text-3xl font-bold">
                お問い合わせ内容の入力
              </h2>
              <p className="text-center mt-3 text-sm">
                ZIONにご興味を持っていただき誠にありがとうございます。
                <br />
                下記フォームからお気軽にお問い合わせください。
              </p>
              <h3 className="text-start mt-5 font-bold">お名前</h3>
              <input
                type="text"
                className="w-full border border-stone-400 mt-4 h-9"
                placeholder=" 山田 太郎"
              />
              <h3 className="text-start mt-5 font-bold">メールアドレス</h3>
              <input
                type="text"
                className="w-full border border-stone-400 mt-4 h-9"
                placeholder=" example@example.com"
              />
              <h3 className="text-start mt-5 font-bold">電話番号</h3>
              <input
                type="text"
                className="w-full border border-stone-400 mt-4 h-9"
                placeholder=" 000-0000-0000"
              />
              <h3 className="text-start mt-5 font-bold">住所</h3>
              <input
                type="text"
                className="w-full border border-stone-400 mt-4 h-9"
                placeholder=" 大阪府〇〇市"
              />
              <div className="flex justify-between">
                <div className="w-64 ">
                  <h3 className="text-start mt-5 font-bold">会社名</h3>
                  <input
                    type="text"
                    className="w-full border border-stone-400 mt-4 h-9"
                  />
                </div>
                <div className="w-64">
                  <h3 className="text-start mt-5 font-bold">部署名</h3>
                  <input
                    type="text"
                    className="w-full border border-stone-400 mt-4 h-9"
                    placeholder=" "
                  />
                </div>
              </div>
              <h3 className="text-start mt-5 font-bold">お問い合わせ内容</h3>
              <textarea
                id="comment"
                name="comment"
                className="border w-full border-stone-400 h-44"
              ></textarea>
              <Link href="/" className="block  mt-8 text-center">
                <button className="text-center shadow-md w-64 py-4  sm:bg-button font-bold after:pl-1  rounded-full hover:opacity-90 duration-500">
                  送信する
                </button>
              </Link>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default Contact;
