import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import styles from "../styles/Home.module.css";

const Home = () => {
  return (
    <div className="font-sans" style={{ color: "#242424" }}>
      <Head>
        <title>ZION</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className="px-5 flex h-16 w-full shadow-md justify-between items-center mx-auto md:px-24 fixed z-10 bg-white ">
        <div>
          <h1>
            <Link href="/" className="font-serif text-4xl">
              ZION
            </Link>
          </h1>
        </div>
        <ul className="flex text-base font-normal">
          <li>
            <Link
              href="/"
              className="no-underline hover:after:visible hover:after:opacity-100 hover:after:-bottom-1 after:duration-300 mr-3 relative inline-block after:absolute after:-bottom-2
               after:left-0 after:content-[''] after:h-2px after:w-full after:bg-under after:opacity-0 after:invisible "
            >
              ホーム
            </Link>
          </li>
          <li>
            <Link
              href="/"
              className="no-underline hover:after:visible hover:after:opacity-100 hover:after:-bottom-1 after:duration-300 mr-3 relative inline-block after:absolute after:-bottom-2
               after:left-0 after:content-[''] after:h-2px after:w-full after:bg-under after:opacity-0 after:invisible "
            >
              施工実績
            </Link>
          </li>
          <li>
            <Link
              href="/"
              className="no-underline hover:after:visible hover:after:opacity-100 hover:after:-bottom-1 after:duration-300 mr-3 relative inline-block after:absolute after:-bottom-2
               after:left-0 after:content-[''] after:h-2px after:w-full after:bg-under after:opacity-0 after:invisible "
            >
              業務内容
            </Link>
          </li>
          <li>
            <Link
              href="/contact"
              className="no-underline hover:after:visible hover:after:opacity-100 hover:after:-bottom-1 after:duration-300  relative inline-block after:absolute after:-bottom-2
               after:left-0 after:content-[''] after:h-2px after:w-full after:bg-under after:opacity-0 after:invisible "
            >
              お問い合わせ
            </Link>
          </li>
        </ul>
      </header>
      <div
        className="block w-full h-screen  "
        style={{ backgroundImage: "url(/apartment-406901_1920.jpg)" }}
      >
        <div
          className="md:text-3xl text-2xl z-9 relative  top-80 md:px-24 font-serif w-fit  px-5"
          data-aos="fade-in"
          data-aos-duration="1000"
          data-aos-easing="ease-in"
          data-aos-once="true"
        >
          <h2 className="md:text-3xl font-bold ">
            洗練された心地良い空間を
            <br className="md:hidden" />
            提供します
          </h2>
          <p className="mt-2 md:text-right md:text-base text-sm ">
            清掃のプロがあなたの空間をよりすばらしいものへと変えます
          </p>
        </div>
      </div>
      {/* ファーストビュー */}
      <section
        className="w-full h-full"
        style={{ backgroundColor: "#006EBA" }}
        data-aos="fade-in"
        data-aos-duration="500"
        data-aos-easing="ease-in"
      >
        <div className=" pt-14 pb-14">
          <div className="bg-white  mx-5 md:mx-24">
            <div
              data-aos="fade-in"
              data-aos-duration="800"
              data-aos-easing="ease-in"
            >
              <h2 className="text-center font-bold pt-8 text-3xl">
                - ABOUT US -
              </h2>
              <p className=" text-sm text-center">ZIONについて</p>
            </div>
            <div
              className="mt-10 md:flex block justify-between md:px-16 px-8 mx-auto"
              data-aos="fade-in"
              data-aos-duration="1000"
              data-aos-easing="ease-in"
            >
              <div className="mt-7 md:mt-16">
                <p className="md:leading-7 leading-5 text-sm md:text-base">
                  ZIONは大阪を中心に美装工事をしている会社です。
                  <br />
                  私達ZIONはお客様に寄り添ったサービス提供できるよう、
                  <br className="md:block hidden" />
                  「親切さ・誠実さ」をモットーに、日々企業活動に取り組んでいます。
                  <br />
                  ハウスクリーニング、美装工事のことでなにかお悩みごと等ございましたら、
                  <br className="md:block hidden" />
                  些細なことでもお問い合わせください。
                </p>
              </div>
              <div className="">
                <div
                  className="mb-8 pb-8 pt-5"
                  style={{
                    position: "relative",
                    maxWidth: "400px",
                  }}
                >
                  <Image
                    src="/vacuum-cleaner-268179_640.jpg"
                    // layout={"responsive"}
                    width={600}
                    height={300}
                    alt="掃除機"
                  />
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>
      {/* Aboutセクション */}
      <section
        className=""
        data-aos="fade-in"
        data-aos-duration="500"
        data-aos-easing="ease-in"
      >
        <h2 className="text-center font-bold md:pt-12 pt-8 text-3xl">
          - SERVICE -
        </h2>
        <p className=" text-sm text-center">業務内容</p>
        <div className="mt-10 ">
          <div
            className="md:flex block mx-auto md:px-24 px-5 justify-between"
            data-aos="fade-in"
            data-aos-duration="500"
            data-aos-easing="ease-in"
          >
            <div
              className="md:pt-0 "
              style={{
                position: "relative",
                width: "100%",
              }}
            >
              <Image
                src="/service-1.jpeg"
                width={600}
                height={300}
                quality={95}
                alt="新築美装"
              />
            </div>
            <div className=" w-full text-center">
              <h1 className=" text-start text-xl mt-2 md:hidden block font-bold">
                新築美装
              </h1>
              <h1 className="text-2xl font-bold mt-10  md:block hidden">
                新築美装
              </h1>
              {/* 画像 */}
              <p className="md:mt-10 mt-4 text-left inline-block md:leading-7 leading-6">
                ホコリや塵、接着剤、無垢材の養生等による日焼
                <br className="md:block hidden" />
                け痕など、新築工事で発生した様々な汚れを
                <br className="md:block hidden" />
                取り除きます。
              </p>
              <Link href="/" className="block md:mt-8 mt-5">
                <button className="text-center shadow-md w-64 py-4 bg-button font-bold after:pl-1 after:content-['>'] rounded-full hover:opacity-80 duration-500">
                  詳細を見る
                </button>
              </Link>
            </div>
            {/* テキスト要素 */}
          </div>
          {/* 新築美装セクション */}

          <div
            className="md:flex block mx-auto md:px-24 px-5 justify-between md:mt-16 mt-10 flex-row-reverse"
            data-aos="fade-in"
            data-aos-duration="500"
            data-aos-easing="ease-in"
          >
            <div
              className="md:pt-0 pt-7 "
              style={{
                position: "relative",
                width: "100%",
              }}
            >
              <Image
                src="/service-2.jpg"
                width={600}
                height={300}
                quality={95}
                alt="外壁洗浄"
              />
            </div>
            <div className=" w-full md:text-center">
              <h1 className=" text-start text-xl mt-2 md:hidden block font-bold">
                外壁洗浄
              </h1>
              <h1 className="text-2xl font-bold mt-10 md:block hidden">
                外壁洗浄
              </h1>

              {/* <p className="mt-10 text-left inline-block leading-7"> */}
              <p className="md:mt-10 mt-4 text-left inline-block md:leading-7 leading-6">
                ビル・マンション・店舗・戸建住宅など、建物
                <br className="md:block hidden" />
                の外壁・屋根部分にこびりついたカビや汚れを
                <br className="md:block hidden" />
                洗い落します。
              </p>
              <Link href="/" className="block md:mt-8 mt-5 text-center">
                <button className="text-center shadow-md w-64 py-4 bg-button font-bold after:pl-1 after:content-['>'] rounded-full hover:opacity-80 duration-500">
                  詳細を見る
                </button>
              </Link>
            </div>
            {/* テキスト要素 */}

            {/* 画像 */}
          </div>
          {/* 外壁洗浄セクション */}
          <div
            className="md:flex block mx-auto md:px-24 px-5 justify-between md:mt-16 mt-10"
            data-aos="fade-in"
            data-aos-duration="500"
            data-aos-easing="ease-in"
          >
            <div
              className="md:pt-0 pt-7 "
              style={{
                position: "relative",
                width: "100%",
              }}
            >
              <Image
                src="/service-3.jpeg"
                width={600}
                height={300}
                quality={95}
                alt="ハウスクリーニング"
              />
            </div>
            {/* 画像 */}
            <div className=" w-full md:text-center">
              <h1 className=" text-start text-xl mt-2 md:hidden block font-bold">
                ハウスクリーニング
              </h1>
              <h1 className="text-2xl font-bold mt-10 md:block hidden">
                ハウスクリーニング
              </h1>
              <p className="md:mt-10 mt-4 text-left inline-block md:leading-7 leading-6">
                キッチン・お風呂・トイレなど、水回りを中心に
                <br className="md:block hidden" />
                普段の掃除では落ちない頑固な汚れを隅々まで清
                <br className="md:block hidden" />
                掃します。
              </p>
              <Link href="/" className="block text-center md:mt-8 mt-5">
                <button className="text-center shadow-md w-64 py-4 bg-button font-bold after:pl-1 after:content-['>'] rounded-full hover:opacity-80 duration-500">
                  詳細を見る
                </button>
              </Link>
            </div>
            {/* テキスト要素 */}
          </div>
          {/* 新築美装セクション */}
        </div>
      </section>
      <section
        data-aos="fade-in"
        data-aos-duration="500"
        data-aos-easing="ease-in"
      >
        <h2 className="text-center font-bold md:pt-14 pt-24 text-3xl">
          - WORKS -
        </h2>
        <p className=" text-sm text-center">施工実績</p>
        <div
          className="md:flex justify-between mx-auto md:px-24 mt-10  px-8 "
          data-aos="fade-in"
          data-aos-duration="500"
          data-aos-easing="ease-in"
        >
          <div className="md:w-works  shadow-xl mb-6 md:block  w-full">
            <div
              style={{
                position: "relative",
                width: "100%",
                height: "200px",
              }}
            >
              <Image src="/works-1.jpeg" layout="fill" alt="新築美装" />
            </div>
            <div className="">
              <time className="text-sm ml-7">2020.08.09</time>
              <p className="text-center mt-3 text-lg">
                〇〇マンションの新築美装を行いました
              </p>
              <Link href="/" className="hover:opacity-80">
                <p className="text-detail text-end mr-10 mt-3 mb-3 md:pb-0 pb-3">
                  詳細を見る
                </p>
              </Link>{" "}
            </div>
          </div>
          <div className="md:w-works w-full  shadow-xl mb-6">
            <div
              style={{
                position: "relative",
                width: "100%",
                height: "200px",
              }}
            >
              <Image src="/works-2.jpeg" layout="fill" alt="新築美装" />
            </div>
            <div className="">
              <time className="text-sm ml-7">2020.08.09</time>
              <p className="text-center mt-3 text-lg">
                〇〇マンションの新築美装を行いました
              </p>
              <Link href="/" className="hover:opacity-80">
                <p className="text-detail text-end mr-10 mt-3 mb-3 md:pb-0 pb-3">
                  詳細を見る
                </p>
              </Link>
            </div>
          </div>
          <div className="md:w-works w-full  shadow-xl mb-6">
            <div
              style={{
                position: "relative",
                width: "100%",
                height: "200px",
              }}
            >
              <Image src="/works-3.jpeg" layout="fill" alt="新築美装" />
            </div>
            <div className="">
              <time className="text-sm ml-7">2020.08.09</time>
              <p className="text-center mt-3 text-lg">
                〇〇マンションの新築美装を行いました
              </p>
              <Link href="/" className="hover:opacity-80">
                <p className="text-detail text-end mr-10 mt-3 mb-3 md:pb-0 pb-3">
                  詳細を見る
                </p>
              </Link>
            </div>
          </div>
        </div>
      </section>
      <section
        className="mt-8 md:h-96 "
        style={{
          backgroundImage: "url(/contact.jpg)",
          backgroundSize: "cover",
        }}
        data-aos="fade-in"
        data-aos-duration="500"
        data-aos-easing="ease-in"
      >
        <h2 className="text-center text-white md:pt-24 pt-16 font-bold md:text-3xl text-2xl">
          まずは無料見積もりまで
        </h2>
        <Link href="/contact" className="block md:mt-12 mt-5 pb-7 text-center">
          <button className="text-center shadow-md w-64 py-4 bg-button font-bold after:pl-1 after:content-['>'] rounded-full hover:opacity-90 duration-500">
            お問い合わせ
          </button>
        </Link>
      </section>
    </div>
  );
};

export default Home;
